# Generated by Django 4.2.16 on 2025-06-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_delivery_cost_order_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
    ]
