# Generated by Django 4.2.16 on 2025-06-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pointshistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointsHistory',
        ),
    ]
