# Generated by Django 4.2.16 on 2025-06-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pointchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointChange',
        ),
    ]
