# Generated by Django 4.2.16 on 2025-06-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
