# Generated by Django 4.2.16 on 2025-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_userpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
