# Generated by Django 4.2.16 on 2025-06-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_report_options_remove_report_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
