# Generated by Django 5.1 on 2025-06-22 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_price_orderitem_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('visitor_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
