# Generated by Django 5.1 on 2025-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_report_total_visitors_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='unique_devices',
            field=models.TextField(default='[]'),
        ),
    ]
