# Generated by Django 5.1 on 2025-06-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_visitorlog_unique_devices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorLog',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_visitors',
        ),
    ]
