# Generated by Django 5.1 on 2025-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_visitorlog_remove_report_total_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('page_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visited_at'], name='api_visitor_visited_ce4756_idx'), models.Index(fields=['ip_address'], name='api_visitor_ip_addr_5d9b96_idx')],
            },
        ),
    ]
